name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python v3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: pytest --html=pytest-report.html .
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: pytest-report
          path: pytest-report.html
      - name: Lint with flake8
        run: flake8 --format=html --htmldir=flake-report .
      - name: Upload flake8 results
        uses: actions/upload-artifact@v3
        with:
          name: flake8-report
          path: flake-report